name: contact
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_analytics: ^10.8.0
  sqflite: ^2.3.2
  change_app_package_name: ^1.1.0
  google_sign_in:
  flutter_bloc:
  shared_preferences: ^2.2.2
  equatable:
  flutter_svg:
  mask_text_input_formatter:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  linkify: ^5.0.0
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  firebase_storage: ^11.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
